"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _categories_grid from './categories-grid.bones.json'
import _featured_ads from './featured-ads.bones.json'
import _latest_ads from './latest-ads.bones.json'

registerBones({
  "categories-grid": _categories_grid,
  "featured-ads": _featured_ads,
  "latest-ads": _latest_ads,
})
